version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: profils-postgres
    environment:
      POSTGRES_DB: profilsdb
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

